# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deck < Formula
  desc "Declarative configuration for Kong"
  homepage "https://github.com/kong/deck"
  version "1.29.0"

  on_macos do
    url "https://github.com/Kong/deck/releases/download/v1.29.0/deck_1.29.0_darwin_all.tar.gz"
    sha256 "fd9ab54f62be376b36feccb74fdf9960c18d394c2b6ab7156bffbf6ebe60aa1f"

    def install
      bin.install "deck"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kong/deck/releases/download/v1.29.0/deck_1.29.0_linux_arm64.tar.gz"
      sha256 "abcf22ce2f582aa734eb35163d5fda7f01060909dd78d1ce8cd5a9dadc27bdef"

      def install
        bin.install "deck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Kong/deck/releases/download/v1.29.0/deck_1.29.0_linux_amd64.tar.gz"
      sha256 "0c77f2030431c1624476623408cde0a68514c8d71a66c6682923c367c89f9616"

      def install
        bin.install "deck"
      end
    end
  end

  test do
    system "#{bin}/deck", "version"
  end
end
