# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deck < Formula
  desc "Declarative configuration for Kong"
  homepage "https://github.com/kong/deck"
  version "1.43.1"

  on_macos do
    url "https://github.com/Kong/deck/releases/download/v1.43.1/deck_1.43.1_darwin_all.tar.gz"
    sha256 "0924d1f66f306dee43c2fa967944372e78f8e85a5dd5390fee091b9b39e62133"

    def install
      bin.install "deck"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kong/deck/releases/download/v1.43.1/deck_1.43.1_linux_arm64.tar.gz"
      sha256 "fc5266dcaa26aae675f07e7346d94e8dc369ca37cfb4f2da5be61fe7474ca703"

      def install
        bin.install "deck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Kong/deck/releases/download/v1.43.1/deck_1.43.1_linux_amd64.tar.gz"
      sha256 "730d5f3fa787be9969658292d7b40623466835342670879caec0b0c86fecee66"

      def install
        bin.install "deck"
      end
    end
  end

  test do
    system "#{bin}/deck", "version"
  end
end
