# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deck < Formula
  desc "Declarative configuration for Kong"
  homepage "https://github.com/kong/deck"
  version "1.65.3"

  on_macos do
    url "https://github.com/Kong/deck/releases/download/v1.65.3/deck_1.65.3_darwin_all.tar.gz"
    sha256 "74c012aacde34f965399028030186bd62141eab057dffdc7f5ddc75843bb24ab"

    def install
      bin.install "deck"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kong/deck/releases/download/v1.65.3/deck_1.65.3_linux_arm64.tar.gz"
      sha256 "58a07755db7c00da27498a2ea415bde2404b46577d2b73064d2f381be38bcc56"

      def install
        bin.install "deck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Kong/deck/releases/download/v1.65.3/deck_1.65.3_linux_amd64.tar.gz"
      sha256 "edca6f57ff8b0145597620f84ccb1cc821bcaec4eabef065d3ad4ac5a4aec481"

      def install
        bin.install "deck"
      end
    end
  end

  test do
    system "#{bin}/deck", "version"
  end
end
